### ISSUE TITLE
Duplicated identifier `IdentityOwner`

### ISSUE THREAD

**Issue by JGiter** [energywebfoundation/ew-did-registry#317]
`IdentityOwner` defined twice - in https://github.com/energywebfoundation/ew-did-registry/blob/02e1796998bb8f255bc9240b006e4bd1fa47594a/packages/did-ethr-resolver/src/implementations/identityOwner.ts#L10 and in https://github.com/energywebfoundation/ew-did-registry/blob/02e1796998bb8f255bc9240b006e4bd1fa47594a/packages/did-resolver-interface/src/models/resolver.ts#L167

**Comment by knzeng-e** [comment]
Thank you @JGiter, the interface should have been removed, I unintentionally restored this during conflict resolution on squashing process
